export const AIRPORTS = [
  { code: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom" },
  { code: "JFK", name: "John F. Kennedy Intl", city: "New York", country: "United States" },
  { code: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France" },
  { code: "DXB", name: "Dubai International", city: "Dubai", country: "UAE" },
  { code: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan" },
  { code: "SYD", name: "Kingsford Smith", city: "Sydney", country: "Australia" },
  { code: "SIN", name: "Changi Airport", city: "Singapore", country: "Singapore" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { code: "LAX", name: "Los Angeles Intl", city: "Los Angeles", country: "United States" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { code: "AMS", name: "Schiphol", city: "Amsterdam", country: "Netherlands" },
  { code: "HKG", name: "Hong Kong Intl", city: "Hong Kong", country: "Hong Kong" },
  { code: "ICN", name: "Incheon Intl", city: "Seoul", country: "South Korea" },
  { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" },
  { code: "BOM", name: "Chhatrapati Shivaji", city: "Mumbai", country: "India" },
  { code: "YYZ", name: "Pearson Intl", city: "Toronto", country: "Canada" },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { code: "SFO", name: "San Francisco Intl", city: "San Francisco", country: "United States" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
];
